[pytest]
filterwarnings =
    ignore:Please use `import python_multipart` instead.:PendingDeprecationWarning
markers =
    asyncio: mark a test as requiring pytest-asyncio
asyncio_mode = auto
asyncio_default_fixture_loop_scope = function
